#!/usr/bin/env ruby
# encoding: utf-8

require_relative 'lib/errwipe'

wiper = Errwipe::Wiper.new do |c|
  c.errbit_url = 'http://errbit-demo.herokuapp.com'

  c.apps = [/Demo/i]

  c.errors = [/Can't connect to MySQL server/,
              /MySQL server has gone away/,
              /Lost connection to MySQL server/,
              /^Timeout::Error: Timeout::Error$/]

  prompt = Errwipe::CredentialPrompt.new
  c.username = prompt.username
  c.password = prompt.password
  puts
end

wiper.perform!
