#!/usr/bin/env ruby
# encoding: utf-8

require_relative 'lib/errwipe/credential_prompt'
require_relative 'lib/errwipe/wiper'


wiper = Errwipe::Wiper.new do |c|
  c.errbit_url = 'https://errbit.puzzle.ch'

  c.apps = [/Hitobito/i]
  
  c.errors = [/Can't connect to MySQL server/,
              /MySQL server has gone away/,
              /Lost connection to MySQL server/,
              /^Timeout::Error: Timeout::Error$/]

  prompt = Errwipe::CredentialPrompt.new
  c.username = prompt.username
  c.password = prompt.password
  puts
end

wiper.perform!
